name: test pipeline
env:
  APPLICAITON_IMAGE_VERSION: "1.0"
  APPLICATION_NAME: "transactions-management-support"
  LAST_COMMIT_HASH: ${{github.sha}}
on:
  push:
    branches:
      - development

jobs:
  build:
    env:
      NAME_OF_THE_STAGE: "build"
    runs-on: ubuntu-latest
    steps:
      - name: list directory before github clone
        run : |
          ls -la

      - name: git copy repository content
        uses: actions/checkout@v1

      - name: list directory after github clone
        run : |
            ls -la

      - name: Print content of current version of github repository
        run : |
          echo "Stage : ${{env.NAME_OF_THE_STAGE}}. Service : ${{env.APPLICATION_NAME}}. Version ${{env.APPLICAITON_IMAGE_VERSION}}. Last commit hash :  ${{env.LAST_COMMIT_HASH}}"
  test:
    env:
      NAME_OF_THE_STAGE : "test"
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Stage Info
        run : |
          echo "Stage : ${{env.NAME_OF_THE_STAGE}}"
      - name: print content of project
        run : |
          ls -la
      - name: Amazon Version echo
        run : |
          aws --version
      - name: ZIP Version echo
        run: |
          zip --version
