name: test pipeline
env:
  APPLICAITON_IMAGE_VERSION : "1.0"
  APPLICATION_NAME          : "transactions-management-support"
  LAST_COMMIT_HASH          : ${{github.sha}}
  EB_PACKAGE_S3_BACKET_NAME : "my-first-deployment-to-amazon"
  EB_APPLICATION_NAME       : "MyFirstElasticBeanstlak"
  DEPLOY_PACKAGE_NAME       : "docker_image_${{github.sha}}"
  DEPLOY_REGION             : "eu-north-1"

on:
  push:
    branches:
      - development
  pull_request:
    branches: 
      - development

jobs:
  build:
    env:
      NAME_OF_THE_STAGE: "build"
    runs-on: ubuntu-latest
    steps:
      - name: list directory before github clone
        run : |
          ls -la

      - name: git copy repository content
        uses: actions/checkout@v1

      - name: list directory after github clone
        run : |
            ls -la

      - name: Print content of current version of github repository
        run : |
          echo "Stage : ${{env.NAME_OF_THE_STAGE}}. Service : ${{env.APPLICATION_NAME}}. \
              Version ${{env.APPLICAITON_IMAGE_VERSION}}. Last commit hash :  ${{env.LAST_COMMIT_HASH}}"
      - name: Check docker availability
        run: |
          docker --version
  test:
    env:
      NAME_OF_THE_STAGE : "test"
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Stage Info
        run : |
          echo "Stage : ${{env.NAME_OF_THE_STAGE}}"
      - name: print content of project
        run : |
          ls -la
      - name: Amazon Version echo
        run : |
          aws --version
      - name: ZIP Version echo
        run: |
          zip --version
