name: test pipeline
env:
  APPLICAITON_IMAGE_VERSION: "1.0"
  APPLICATION_NAME: "transactions-management-support"
  LAST_COMMIT_HASH: ${{github.sha}}
on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print content of current version of github repository
        run : |
          echo "Build ${{env.APPLICATION_NAME}}. Version ${{env.APPLICAITON_IMAGE_VERSION}}. Last commit hash :  ${{env.LAST_COMMIT_HASH}}"
  test:
    runs-on: ubuntu-latest
    steps:
      - name: print content of project
        run : |
          ls -la